# Generated by Django 5.2.6 on 2025-09-17 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculate', '0003_remove_transaction_id_alter_transaction_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
    ]
